environment:
  DOCKER_APT_VERSION: "${DOCKER_VERSION:-1.0.0}-1-apt"

tasks:
  default:
    requires: [package]

  package:
    requires: ["package-apt-config?"]

  package-apt-config:
    requires: [":apt:pre-config"]
    required_by: [":apt"]
    script: echo "docker==${DOCKER_APT_VERSION}" > "${EBRO_ROOT}/.cache/apt/packages/docker.txt"
    when:
      check_fails: test -f "${EBRO_ROOT}/.cache/apt/packages/docker.txt"
      output_changes: echo "docker==${DOCKER_APT_VERSION}"

  package-apk-config:
    requires: [":apk:pre-config"]
    required_by: [":apk"]
    script: echo "docker==${DOCKER_APT_VERSION}" > "${EBRO_ROOT}/.cache/apk/packages/docker.txt"
    when:
      check_fails: test -f "${EBRO_ROOT}/.cache/apk/packages/docker.txt"
      output_changes: echo "docker==${DOCKER_APT_VERSION}"
